### ISSUE TITLE
Can't add a new open bookcase point

### ISSUE THREAD

**Issue by Janabau** [pietervdvn/MapComplete#118] opened 2020-09-08 09:26 UTC
Hi, I tried the Open Bookcase, but when I locate the point and press +, I get "You clicked somewhere where no data is known yet. Please, read all your OpenStreetMap-messages before adding a new point." I read my messages and there was none related to the MapComplete, still could not add one.

**Comment by pietervdvn** [comment] 2020-09-08 09:45
Hey,

In the case that someone is adding too much points of poor quality, there needs to be an 'emergency break' to let this contributor know.

However, MapComplete _can not_ read your OSM-messages, but it can see you have _unread_ messages which we use to stop people from adding new points.

The solution is to mark all you messages in your OSM-inbox as read, then you'll be able to add a new bookcase.

**Comment by pietervdvn** [comment] 2020-09-08 09:45
(Closing as intended behaviour)

**Closed by pietervdvn** 2020-09-08 09:45 UTC
