### ISSUE TITLE
Background imagery disappears 

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1481] opened 2023-06-27 12:07 UTC
While working in mapcomplete, with an imagery background layer. The map will just go blank at some point

I seem to have found a way to reprod it.
https://drive.proton.me/urls/CGJD4G3R28#X6llxWqqh6mH (android, chrome)
It seems like it can happen if you choose a background imagery layer, then add a node and pick it's exact location. Then edit some stuff. And all of a sudden the background layer just goes blank and can't be recovered without a refresh

**Comment by CaldeiraG** [comment] 2024-02-20 11:21
Adding that this happens frequently while doing a lot of changes, mainly in the maxspeed layer for me but can happen in other layers if you're "adding too much information", I don't really have a better way to put it

**Comment by pietervdvn** [comment] 2024-02-20 11:23
I suspect that this is a browser-specific issue. What browsers and OS's are you all using?

**Comment by CaldeiraG** [comment] 2024-02-20 11:34
Chromium-based (Vivaldi) on Windows 10/11, had a bit of a stress test on FF on Windows 11 and I couldn't reproduce the issue 🙃

**Comment by pietervdvn** [comment] 2024-02-20 12:45
(I have to admit that I sometimes have similar problems with firefox, if the browser often and quickly reloads the page because I'm developing)

**Comment by pietervdvn** [comment] 2024-04-23 22:37
Duplicate of #1649

**Closed by pietervdvn** 2024-04-23 22:37 UTC
Labels: bug, UI
