### ISSUE TITLE
Uploading multiple images UI stuck

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1472] opened 2023-06-18 04:10 UTC
Steps to reprod: make sure that you're either on a slow connection or artificially slow it using devtools.

Go to any theme, select an object to add images to.

Select one image to upload and upload. Then immediately pick and other image and upload that as well.
Now you have 2 images uploading.
Everything will work correctly except that the "2 images uploading" notice will never go away until you close that osm object's dialog
![Screenshot_20230618_055424_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/db1773ad-1371-4ca3-9cd6-91a7674ea1ac)

**Comment by pietervdvn** [comment] 2023-07-16 01:13
Duplicate of #1492

**Comment by pietervdvn** [comment] 2024-04-23 22:30
Has been fixed a while ago

**Closed by pietervdvn** 2024-04-23 22:30 UTC
Labels: bug, UI
