### ISSUE TITLE
Multiple nodes created

### ISSUE THREAD

**Issue by RobinLinde** [pietervdvn/MapComplete#698] opened 2022-03-11 19:00 UTC
First [changeset](https://www.openstreetmap.org/changeset/118279228) looks mostly fine, but added an extra [node](https://www.openstreetmap.org/node/9566045390) with only the tag  `emergency=defibrillator`. Then after opening my browser a couple of times two changesets ([1](https://www.openstreetmap.org/changeset/118356139) and [2](https://www.openstreetmap.org/changeset/118356986)) with exactly the same node in the same spot.
Earlier today I [tried to add a bench](https://www.openstreetmap.org/changeset/118368424), and it seems to have added it at the same spot, instead of what I picked, along with the tag  `emergency=defibrillator`.

Not entirely sure what happened here, but seems vaguely reminiscent of #659

**Comment by pietervdvn** [comment] 2023-06-11 23:03
Something probably caused to execute the upload twice, e.g. because MC thought it was not uploaded properly.

As this is very hard to reproduce, it seems like it didn't resurface and that much of this code changed with the MapLibre port, I'm gonna close this issue.

**Closed by pietervdvn** 2023-06-11 23:03 UTC
