### ISSUE TITLE
Split roads

### ISSUE THREAD

**Issue by arnodeceuninck** [pietervdvn/MapComplete#408] opened 2021-07-08 12:04 UTC
When some properties of a road change halfway (e.g. the surface), the road has to be splitted

- Research how other map providers split roads
- Implement this in MapComplete

**Comment by tordans** [comment] 2021-07-12 15:08
>Research how other map providers split roads

I find the solution https://zlant.github.io/parking-lanes/#18/52.47906/13.43284 uses quite feasible. However, you have to find it, which is one of the bigger issues with this app IMO. Click edit on the bottom right, then select a way, click cutting icon in the panel on the top right, then the cutting icon on the road. Changes are only saved if you click save (top right).

The cutting icons on the road seem to appear where nodes in the road are, which is always in intersections, which is IMO a very easy and smart way to start.

![image](https://user-images.githubusercontent.com/111561/125311220-88081380-e333-11eb-8fa2-ffd18700fec5.png)

**Comment by pietervdvn** [comment] 2021-07-14 09:21
Duplicate of #171

**Comment by pietervdvn** [comment] 2021-07-14 13:00
Closed because duplicate

**Closed** 2021-07-29 13:17 UTC
Labels: OSOC21, OSOC21:Cycling-OVL
