### ISSUE TITLE
Wasserbrunnen (Pumpen): i) check_date-Datumseingabe "heute" ist defekt und ii) Text für manuelle Datumseingabe ist falsch

### ISSUE THREAD

**Issue by Wikinaut** [pietervdvn/MapComplete#1035] opened 2022-08-19 06:15 UTC
1. "heute" funktioniert nicht
2. Manuelle Datumseingabe: der beschreibende Text ist falsch, denn als Datumsformat muss ganz offensichtlich JJJJ-MM-TT benutzt werden. 

![grafik](https://user-images.githubusercontent.com/1151915/185554904-79df2a3c-791c-47c3-a4f9-dff15712ec81.png)

Webseite

https://mapcomplete.osm.be/theme?z=20&lat=52.47725&lon=13.33076&userlayout=https%3A%2F%2Ftordans.github.io%2FMapComplete-ThemeHelper%2FOSM-Berlin-Themes%2Fman_made-walter_well-status-checker%2Ftheme.json&language=de#node/966049534

Browser: Firefox 103.0.2

**Comment by pietervdvn** [comment] 2022-08-19 06:30
Hi,

The date picker will show up in the regional date format.

Selecting 'today' and saving will set the date of today to the object, so this works as intended. It'll won't set a date in the datefield below.

**Comment by tordans** [comment] 2022-08-19 19:05
I agree, the UI does work correctly (1 and 2), however it is confusing:

When the check_date input is empty, the placeholder text explains the format (which is yyyy-mm-dd) that has to be used for the input "starting with the year". However, the date picker right below shows the local date format. The fact that one is a placeholder and one a helper, that will fill the placeholder is hard to understand.

However, I don't see an easy solution that does not require a custom UI element with added actions like "write format manually" vs. "use date picker". Which is AFAIK hard to build at this place of the UI.

**Comment by tordans** [comment] 2022-08-19 19:05
I agree, the UI does work correctly (1 and 2), however it is confusing:

When the check_date input is empty, the placeholder text explains the format (which is yyyy-mm-dd) that has to be used for the input "starting with the year". However, the date picker right below shows the local date format. The fact that one is a placeholder and one a helper, that will fill the placeholder is hard to understand.

However, I don't see an easy solution that does not require a custom UI element with added actions like "write format manually" vs. "use date picker". Which is AFAIK hard to build at this place of the UI.

**Comment by Wikinaut** [comment] 2022-08-27 15:44
For me, it did not work.

**Comment by Wikinaut** [comment] 2022-08-27 17:19
It does not work to click "heute" (today).

**Comment by tordans** [comment] 2022-08-28 03:52
@Wikinaut can you share Browser(version), system and you click-by-click steps. This will help debugging, since we cannot reproduce it, yeet.

**Comment by Wikinaut** [comment] 2022-08-30 12:48
This not working:

Firefox 104.0
Linuxmint 20.03

Klick (1)
Klick (2) - not working

![grafik](https://user-images.githubusercontent.com/1151915/187440502-d0defb82-2062-4fe6-b36c-3cb039c1c51e.png)

**Comment by Wikinaut** [comment] 2022-08-30 12:49
Please reopen.

**Comment by Wikinaut** [comment] 2022-08-30 12:51
When I manually enter the date as shown (1), then I have to click the select button, than I can click (4) and the result is saved.

Please observe the differences between (2) and (3)!

![grafik](https://user-images.githubusercontent.com/1151915/187441039-cdcf82b2-cb2c-4099-9070-5299f7d5d9ab.png)

**Comment by Wikinaut** [comment] 2022-08-30 12:52
It looks to me, that the LOCALE / Browser language / system language is not correctly treated.

**Comment by Wikinaut** [comment] 2022-08-30 12:54
It looks to me, that the LOCALE / Browser language / system language is not correctly treated.

The object is https://www.openstreetmap.org/node/1169056641

**Comment by pietervdvn** [comment] 2022-08-30 18:24
Hi,

There are multiple issues at play here.

First of all, yes, "Heute" does not work. I'm fixing that.

For your second screenshot: number 1 is the textfield for those who want to manually input a date. 2 is the timepicker handled by the browser, 3 is the actual tag that will be added to OSM. In OSM, we use 'YYYY-MM-DD' as format, hence why it is formatted this way and why it is **always** shown in this format in the textfield, no matter the locale.

**Comment by pietervdvn** [comment] 2022-09-03 18:34
Fixed in 816670fe49ef12c88b00b1fb450849f51361e62f

**Closed by pietervdvn** 2022-09-03 18:34 UTC
