### ISSUE TITLE
AED change icon when checked today

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1426] opened 2023-05-30 14:48 UTC
I noticed that both on the regular version and the upcoming maplibre version that if you mark an AED as 'check today'. It doesn't actually change the color of the icon to the bright green one. Until you refresh the page.

**Comment by pietervdvn** [comment] 2023-06-03 22:56
The 'recently surveyed' is done by a calculated tags. Calculated tags are _not_ updated when the source tags update, hence the color does not change.

**Comment by pietervdvn** [comment] 2023-06-11 21:21
Duplicate of #287

**Closed by pietervdvn** 2023-06-11 21:21 UTC
Labels: bug, Theme ideas, UI
