### ISSUE TITLE
amenity = drinking_water is too slow

### ISSUE THREAD

**Issue by filipca** [pietervdvn/MapComplete#1764] opened 2024-01-23 19:19 UTC
In my neighbourhood it works.
But when I move the map to the Belgian Coast it is very slow or does not respond at all when I zoom in and click on a fountain.
A hard refresh does not help.
https://mapcomplete.org/drinking_water?z=15.7&lat=51.12020385453906&lon=2.6602627321292402#node/4578197313

**Comment by pietervdvn** [comment] 2024-01-23 21:26
This is caused by a bug only affecting 'drinking_water', fixed in a5276eb4e67ed939e5b34ad7ffca61d6e41d679d

**Closed** 2024-01-29 13:25 UTC
Labels: Themes, Performance
