### ISSUE TITLE
Bug: Pop-up image blocks everything

### ISSUE THREAD

**Issue by Tauvic** [pietervdvn/MapComplete#471] opened 2021-09-12 07:14 UTC
On mapcomplete benches for example. The pop-up for each bench also shows a little map of the bench in it's surroundings. But this image sometimes is too big and on top of everything else, blocking the complete view.

#bug

**Comment by pietervdvn** [comment] 2021-09-12 18:23
This is a duplicate of #464 and is fixed in develop

**Closed by pietervdvn** 2021-09-12 18:23 UTC
