### ISSUE TITLE
Open changeset / how to close the changeset

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#116] opened 2020-08-28 04:51 UTC
Hi, I just testet the app with the cycle theme. OSM now says the changeset is open, see https://www.openstreetmap.org/changeset/90055323#map=19/52.47905/13.44590.

I could not find any information in the app or here about when the changeset gets closed.

My understand is, only closed changesets are actually used in osm, right?

Suggestions
- Add explanation about how this works to the interface
- … and to the GitHub readme
- And, in case I need to do something in the app, make this more prominent.

Thanks for this very promising and helpful approach to mapping OSM!

**Comment by pietervdvn** [comment] 2020-08-28 10:51
Hey,

Nit closing changesets is the intended behaviour.

See https://github.com/pietervdvn/MapComplete/blob/master/README.md#uploading-changes

**Closed by pietervdvn** 2020-08-28 10:51 UTC
