### ISSUE TITLE
Can't select object to edit

### ISSUE THREAD

**Issue by tuxayo** [pietervdvn/MapComplete#1458] opened 2023-06-14 01:34 UTC
Hi :) With other OSM contributors in my city we just discovered how amazing MapComplete is to add and complete surveillance cameras in the field. Mapping directional cameras was a pain, now it's a breeze <3

Here there is an issue:
https://mapcomplete.osm.be/surveillance.html?z=21&lat=43.23138&lon=5.437805&language=en
Whether on my phone or a computer, I can't select 3 of the 5 cameras on the building. Actually on the phone only two (those with a direction at the time of opening this ticket) of them I wasn't able to select. But on the PC now, I'm can't select the one above the 2 without direction.
So the 3 problematic are the 3 on the west side of the little building that has 3 cameras on it.

**Comment by pietervdvn** [comment] 2023-06-14 18:46
Hi,

The direction overlay causes some bugs, so I've disabled this layer. Duplicate of #1335

**Closed by pietervdvn** 2023-06-14 18:46 UTC
