### ISSUE TITLE
Add new input type for 'collection_times' in post boxes

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1711] opened 2023-11-16 21:50 UTC
Can't base opening_hours input type because collection times aren't about periods but specific times, usually.
https://wiki.openstreetmap.org/wiki/Key:collection_times

Not sure if a regular text input is best here or if there's a better solution

**Comment by InsertUser** [comment] 2023-11-19 16:36
See also #757

**Comment by pietervdvn** [comment] 2023-11-19 16:58
Duplicate of #757

**Closed by pietervdvn** 2023-11-19 16:58 UTC
Labels: enhancement, Themes, UI
