### ISSUE TITLE
Change selected element highlight icon

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1203] opened 2022-12-28 21:04 UTC
The dot is currently very bright(/large) and therefore distracting. I would suggest either

- **semi-transparent filled circle** (not to be confused with healthcare/motorway/military/commercial fill on Carto, or own cursor).
![image](https://user-images.githubusercontent.com/67521919/209865834-bf7ea4fb-405e-45f4-92bc-3615648a10a3.png)
![image](https://user-images.githubusercontent.com/67521919/209866313-e88f38c3-43dd-4bad-acfa-1ba5fcd4aa8f.png)

- **smaller, regular filled circle**. can have less bright red color.
![image](https://user-images.githubusercontent.com/67521919/209866401-5867a619-5a9d-4117-8c25-bfa5a0f6fc62.png)

- **hollow circle**. can have semi-transparent fill like on OSM. (could also highlight current task icon with this instead if you want to)

![image](https://user-images.githubusercontent.com/67521919/209867398-122e9fa4-bcd1-4327-b192-639e1d77cf8c.png)

- (Alternatively, a green circle with white pencil icon could be used like with the Add object icon - not too sure how this would be implemented or if this is intuitive, since the user normally needs to click the Add object icon to actually start adding an object)

Was; https://github.com/pietervdvn/MapComplete/commit/42bd3013892f8bbbff6461f1e795b426af7a6b30#commitcomment-94454255

--

Edit: When viewing the map of touristic maps and zooming out, this highlight moves behind the task icon, making it a halo around the task icon in some cases. What is intended? Always below icon or always behind icon?
![image](https://user-images.githubusercontent.com/67521919/209889569-bf4b99df-007e-437d-8537-384e9469b6a7.png)
https://mapcomplete.osm.be/maps?z=18&lat=51.98329&lon=5.902431&language=nl#node/3411724821

**Comment by pietervdvn** [comment] 2023-06-15 14:17
Fixed by the MapLibre port

**Closed by pietervdvn** 2023-06-15 14:17 UTC
Labels: enhancement, low-priority, UI

**Comment by danieldegroot2** [comment] 2023-06-15 16:07
Thanks. It seems some themes (e.g. Benches, A map of maps) do not inherit the new pulsating grey glow effect which other themes (Hotels, AEDs) have. They have no glow effect whatshowever. Is this intended?

**Comment by pietervdvn** [comment] 2023-06-27 18:47
The 'pulsating glow' is caused by a CSS-class on the _background_ pin, e.g. the circle or the square that is placed underneath many icons.

The benches and maps provide their _own_ circle, hence they don't have the pulsating effect yet. They will receive it in the future.
